version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/prisma
    command: >
      bash -c "npx prisma migrate deploy && 
               npm run start:dev"
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
