name: Generate Docs

on:
  pull_request:
    branches:
      - main 

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install typescript typedoc --save-dev

    - name: Generate documentation
      run: npm run docs

    - name: Commit and push documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b gh-pages
        git add -f docs/*
        git commit -m "Update documentation"
        git push -u origin gh-pages